version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "LambdaUnAdminFunction"
s3_bucket = "lambdassam"
s3_prefix = "lambdaunadminfunction"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
